
[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 11.25

[colors.primary]
background = "#1e1e1e"
foreground = "#ff5555"

[colors.normal]
black   = "#1e1e1e"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[colors.bright]
black   = "#6272a4"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#d6acff"
magenta = "#ff92df"
cyan    = "#a4ffff"
white   = "#ffffff"

